### ISSUE TITLE
Database error with space in name

### ISSUE THREAD

**Issue by vidyava** [eternity336/PalworldServerMonitor#2]
Hello,
Just wanted to let you know that this runs into some issues if a player has a space in their name. In particular, this line:
```
players = [line.split(',') for line in run_command("ShowPlayers").split()][1:]
```
Would produce this error:
```
Error: Incorrect number of bindings supplied. The current statement uses 4, and there are 2 supplied.
```

I ended up changing it to:
```
    players = [line.split(',') for line in run_command("ShowPlayers").split('\n')][1:]
...
    if len(players) == 4:     
       cur.executemany("REPLACE INTO players VALUES(?,?,?,?)", players) 
```
because splitting on newline grabbed an extra line at the end and tried inserting that too. There's probably a better way to handle it, but this has been working.

Thanks for the great program!

**Comment by eternity336** [comment]
Thank you for the suggestion.  I made the fix with a slight difference.  I made a check to make sure the split had three initially in the array.  Your suggestion only works if you have 4 players online, otherwise it will not save to the db.  Great catch on the spaces issue though.  I hadn't come a crossed that yet.  So should be fine now.

**Comment by eternity336** [comment]
I'm going to consider this closed for now.
